print("Hissnsss...")
print()
print("love ya kitty")
print("boobs")
print("\n")
print("Pussy cat, pussy cat\nwhere have you been?")
print()
print("I've been to London\nto look at the queen.")
print("\n")
print("Pussy cat,","pussy cat","where have you been?")
print("\n")
print("My name is","Python",end=" ")
print("Monty Python")
print("I love ",end=" ")
print("Laura,\nyou are amazing")
print("FGmh kjkh",end="2",sep="-")
print("niHJ!")
print("my","name","is","wesley",sep="-")
print("\n")
print("My", "name","is",sep="_",end="*")
print("Monty","Python",sep="*",end="*\n")
print("abc")
print("\n")
print("Literals")
print("2")
print(2)
print("111111\n111_123_456")
print("-11111")
print(0O777)
print(0x999)
print(4.)
print(.4)
print(4)
print(5.4e10)
print("Planck's constant which is denoted by h")
print(6.62607e-34)
