print("Day 1")
print()
print("Pussy cat, pussy cat\nwhere have you been?")
print()
print("I've been to london\nto look at the queen.")
print("Pussy cat,","pussy cat","where have you been?")
print("My name is","Monty")
print("Monty Python")
print("My name is","Python ",end="")
print("Monty Python")
print("Hallo Ik ben Wes ",end="")
print("Ik heb sap voor jou")
print("My name is ",end="")
print("Monty Python")
print("My","name","is","Monty","Python",sep="-")
print()
print("My","name","is",sep="_",end="*")
print("Monty","Python",sep="*",end="*\n")
print()
print("Day 2")
print()
print("2")
print(2)
print("11_111_111")
print(11111111)
print(-11111111)
print(+11111111)
print(0o123)
print(0x123)
print(3E8)
print("Planck's Constant 6.62607E-34")
print(6.62607E-34)
print(0.0000000000000000000001)
print("I like \"Monty Python\"")
print('I like "Monty Python"')
print('I\'m Monty Python')
print("I’m Monty Python")
